version: '3.8'

services:
  charbox-prod:
    build: ./
    container_name: mork_borg_online_sheet
    restart: unless-stopped
    ports:
      - "8080:80"
    networks:
      network:
        ipv4_address: 172.31.0.41
    deploy:
      resources:
        limits:
          memory: 75M

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.0.0/16
          gateway: 172.31.0.1
