version: '3.8'

services:
  charbox-prod:
    build: ./
    container_name: mork_borg_online_sheet
    restart: unless-stopped
    ports:
      - "4141:4141"
    deploy:
      resources:
        limits:
          memory: 75M

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.32.0.0/16
          gateway: 172.32.0.1
